name: LINT
on:
  push:
    branches:
      - main
      - fix/cicd
  pull_request:

permissions:
  contents: read
  pull-requests: read
  checks: write
  # Optional: allow read access to pull request. Use with  option.

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: setup_config
        run: |
          git config --global url."https://huchao66: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@github.com".insteadOf "https://github.com"
          cat ~/.gitconfig
          go mod tidy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
