name: Go Build & Test
on:
  push:
    branches:
      - main
      - fix/cicd
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build And Test
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/RiemaLabs/nubit-kzg
      GH_ACCESS_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.3'
      - run: |
          git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
          go mod tidy
          go get github.com/ipfs/go-cidutil
    
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test
    
